[manifest]
version = "1.1.0"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
match_indent = true
position = "before"
pattern = '''local t = create_UIBox_generic_options({back_func = 'options',contents = {create_tabs('''
payload = '''
if not SMODS then
    tabs[#tabs+1] = {
        label = require('zoomer.locale').translate('zoomer_settings_tab'),
        tab_definition_function = require('zoomer.config_ui').create_config_tab
    }
end
'''